[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.20"

[dependencies]
"@openzeppelin-contracts" = "5.3.0"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
